### ISSUE TITLE
The result was not so good.

### ISSUE THREAD

**Issue by Yuanhong200727** [tijiang13/InstantAvatar#16]
Hey,sir.When I converted `male-1-plaza.mp4` in people_snapshot datasets to a series of pngs,saving it to `myData/images` and run `bash ./bash/run-neuman-demo.sh`(I have changed codes in the file ),the result was not so good:
![003209](https://github.com/tijiang13/InstantAvatar/assets/117512740/fd1432a0-88d3-4534-8b48-279b5ade9fb9)
And here is the codes in `run-neuman-demo.sh`:
```
experiment="baseline"
SEQUENCES=("myData")
for SEQUENCE in ${SEQUENCES[@]}; do
    dataset="myModel/$SEQUENCE"
    bash scripts/custom/process-sequence.sh ./data/custom/$SEQUENCE male
    python fit.py --config-name SNARF_NGP_fitting dataset=$dataset experiment=$experiment deformer=smpl train.max_epochs=30
    python train.py --config-name demo dataset=$dataset experiment=$experiment deformer.opt.cano_pose="a_pose" train.max_epochs=30
    python novel_view.py --config-name demo dataset=$dataset experiment=$experiment deformer.opt.cano_pose="a_pose"
    python animate.py --config-name demo dataset=$dataset experiment=$experiment deformer.opt.cano_pose="a_pose"
done  
```
The config file's content is here(which was similar with male-3-casual.yaml):
```
_target_: instant_avatar.datasets.custom.CustomDataModule
name: myModel
subject: myData
gender: male
opt:
  dataroot: ./data/custom/${dataset.subject}/
  subject: ${dataset.subject}
  train:
    num_workers: 16
    batch_size: 1
    start: 0
    end: 212
    skip: 2
    downscale: 1
    sampler: ${sampler}
    fitting: ${model.opt.optimize_SMPL.enable}
    refine: ${model.opt.optimize_SMPL.is_refine}
  val:
    num_workers: 16
    batch_size: 1
    start: 213
    end: 213
    skip: 2
    downscale: 1
  test:
    num_workers: 16
    batch_size: 1
    start: 213
    end: 388
    skip: 2
    downscale: 1
```
I've tried to train more epoches,but it wasn't better.I also ran the code with my own video,but the result was same.
Here is the message printed when runing `run-neuman-demo.sh`:
[outmessage.txt](https://github.com/tijiang13/InstantAvatar/files/11523887/outmessage.txt)
